version: '3.8'

services:

  #DATABASES--------------------------------------------------------------
  db-postgres:
    image: postgres
    ports:
      - 5432:5432 #Estos puertos son solo para desarrollo, deberan quitarse en produccion
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
  
   
  #------------------------------------------------------------------------
  #BACKENDS----------------------------------------------------------------
  backend:
    build: './backend/app'
    depends_on:
      - db-postgres
    ports: 
      - 8080:8080 #Estos puertos son solo para desarrollo, deberan quitarse en produccion
    volumes:
       - './backend/app:/app'
  

  #------------------------------------------------------------------------



